# Generated by Django 2.2.6 on 2019-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=20)),
                ('portrait', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('area', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('student', models.CharField(max_length=4)),
                ('worktime', models.DateField()),
                ('school', models.CharField(max_length=40)),
                ('admdate', models.DateField()),
                ('gradtime', models.DateField()),
                ('prof', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=60)),
                ('selfdes', models.CharField(max_length=150)),
                ('shejiao', models.CharField(max_length=200)),
                ('type_work', models.CharField(max_length=50)),
                ('nature_work', models.CharField(max_length=20)),
                ('expecte_salary', models.CharField(max_length=20)),
                ('low_salary', models.CharField(max_length=20)),
                ('work_city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('available_time', models.DateField()),
                ('reg_time', models.DateField()),
            ],
        ),
    ]
