# Generated by Django 2.2.6 on 2019-10-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='label',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='selfdes',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='shejiao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
