# Generated by Django 2.2.5 on 2019-10-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0002_auto_20191011_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='小熊猫', max_length=20, null=True),
        ),
    ]
