# Generated by Django 2.2.5 on 2019-10-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0002_auto_20191005_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=80)),
                ('cname', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='recruitment/%Y/%m/%d/')),
                ('aname', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=30)),
                ('scale', models.CharField(max_length=30)),
                ('phases', models.CharField(max_length=30)),
                ('welfare', models.CharField(max_length=30)),
            ],
        ),
    ]
