# Generated by Django 2.2.5 on 2019-10-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='小熊猫', max_length=10)),
                ('age', models.CharField(default=0, max_length=3)),
                ('sex', models.CharField(default=1, max_length=20)),
                ('school', models.CharField(max_length=40, null=True)),
                ('prof', models.CharField(max_length=50, null=True)),
                ('education', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
                ('next', models.CharField(max_length=20)),
            ],
        ),
    ]
