# Generated by Django 2.2.5 on 2019-10-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('recruitment', models.CharField(max_length=40)),
                ('pay', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=10)),
                ('attract', models.TextField(max_length=500)),
                ('describe', models.TextField(max_length=600)),
                ('workplace', models.CharField(max_length=60)),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('sex', models.CharField(max_length=20, null=True)),
                ('birthday', models.DateField(null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('student', models.CharField(max_length=4, null=True)),
                ('worktime', models.CharField(max_length=30, null=True)),
                ('school', models.CharField(max_length=40, null=True)),
                ('admdate', models.DateField(null=True)),
                ('gradtime', models.DateField(null=True)),
                ('prof', models.CharField(max_length=50, null=True)),
                ('education', models.CharField(max_length=50, null=True)),
                ('selfdes', models.CharField(max_length=150, null=True)),
                ('shejiao', models.CharField(max_length=200, null=True)),
                ('type_work', models.CharField(max_length=50, null=True)),
                ('nature_work', models.CharField(max_length=20, null=True)),
                ('expecte_salary', models.CharField(max_length=20, null=True)),
                ('low_salary', models.CharField(max_length=20, null=True)),
                ('work_city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('available_time', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
                ('next', models.CharField(max_length=20)),
            ],
        ),
    ]
