# Generated by Django 2.2.5 on 2019-10-11 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='phone',
            field=models.CharField(default="1", max_length=11),
            preserve_default=False,
        ),
    ]
