# Generated by Django 2.2.5 on 2019-10-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=32)),
                ('recruitment', models.CharField(max_length=40)),
                ('pay', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=10)),
                ('attract', models.TextField(max_length=500)),
                ('describe', models.TextField(max_length=600)),
                ('workplace', models.CharField(max_length=60)),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
    ]
