# Generated by Django 2.2.5 on 2019-10-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_postjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, null=True)),
                ('student', models.CharField(max_length=4, null=True)),
                ('worktime', models.CharField(max_length=30, null=True)),
                ('school', models.CharField(max_length=40, null=True)),
                ('admdate', models.DateField(null=True)),
                ('gradtime', models.DateField(null=True)),
                ('prof', models.CharField(max_length=50, null=True)),
                ('education', models.CharField(max_length=50, null=True)),
                ('selfdes', models.CharField(max_length=150, null=True)),
                ('shejiao', models.CharField(max_length=200, null=True)),
                ('type_work', models.CharField(max_length=50, null=True)),
                ('nature_work', models.CharField(max_length=20, null=True)),
                ('expecte_salary', models.CharField(max_length=20, null=True)),
                ('low_salary', models.CharField(max_length=20, null=True)),
                ('work_city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('available_time', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
